name: test workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: My action
      uses: Andre601/repository-sync@master
      env:
        PAT: ${{ secrets.PAT }}
        EMAIL: ${{ secrets.EMAIL }}
        USER: Andre601
        OWNER: Andre601
        REPO: repository-sync-backup
        TARGET_FOLDER: backup
        EXCLUDE: 'README.md'
        PUSH_MESSAGE: 'Updating target repo'
