name: test workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: My action
      uses: Andre601/repository-sync@master
      with:
        PAT: ${{ secrets.PAT }}
        EMAIL: ${{ secrets.EMAIL }}
        USER: Andre601
        SRC_OWNER: Andre601
        SRC_REPO: repository-sync
        TARGET_OWNER: Andre601
        TARGET_REPO: repository-sync
        TARGET_FOLDER: backup
        EXCLUDE: 'README.md'
        PUSH_MESSAGE: 'Updating target repo'
